/**
 * To check the capacity of students in three different colleges and the revenue generated by them.
 */
package com.gqt.corejava.Arrays;

import java.util.Scanner;
/**
 * @author Abhilash Reddy
 * @category Array
 * @description This program is used to show Medical, Engineering, Degree college students and to calculate revenue generated by them.
 */
class Education{
	Scanner sc = new Scanner(System.in);
	long arr[][][];
	long medical;
	long engineering;
	long degree;
	long revenue;
	void createArray() {
	System.out.println("Enter number of colleges: ");
	int n = sc.nextInt();
	arr = new long [n][][];
	for(int i=0;i<arr.length;i++) {
		System.out.println("Enter the number of classrooms in college: " + (i+1));
		arr[i] = new long[sc.nextInt()][];
	}
	for(int i=0;i<arr.length;i++) {
		System.out.println("Inside college: " + (i+1));
		for(int j=0;j<arr[i].length;j++) {
			System.out.println("Enter the number of students in  classroom: " + (j+1) );
			arr[i][j] = new long[sc.nextInt()];
		}
	}
	System.out.println("Array created");
	System.out.println("-------------");
	}
	void collectData() {
		System.out.println("Enter the Medical college fee: ");
		medical = sc.nextLong();
		System.out.println("Enter the Engineering college fee: ");
		engineering = sc.nextLong();
		System.out.println("Enter the Degree college fee: ");
		degree = sc.nextLong();
		for(int i=0;i<arr.length;i++) {
			System.out.println("Inside college: " + (i+1));
			for(int j=0;j<arr[i].length;j++) {
				System.out.println("Inside classroom: " + (j+1));
				for(int k=0;k<arr[i][j].length;k++) {
					if(i==0) {
					System.out.println("The college fee of student: " + (k+1) + " is assigned" );
					arr[i][j][k] = medical;
					}
					else if(i==1){
						System.out.println("The college fee of student: " + (k+1) + " is assigned" );
						arr[i][j][k] = engineering;
					}
					else {
						System.out.println("The college fee of student: " + (k+1) + " is assigned");
						arr[i][j][k] = degree;
					}
					revenue += arr[i][j][k];
				}
			}
		}
	System.out.println("Data collected");
	System.out.println("--------------");
	}
	void displayData() {
		for(int i=0;i<arr.length;i++) {
			System.out.println("Inside college: " + (i+1));
			for(int j=0;j<arr[i].length;j++) {
				System.out.println("Inside classroom: " + (j+1));
				for(int k=0;k<arr[i][j].length;k++) {
					System.out.println("The college fee of student :" + (k+1) + " is " + arr[i][j][k]);
				}
			}
		}
		System.out.println("Overall Revenue is :" + revenue);
	}
}
public class EducationalTrust {

	/**
	 * @param args
	 * @description This Source code is used to retrive or call the methods to perform operations
	 */
	public static void main(String[] args) {
		Education t = new Education();
		t.createArray();
		t.collectData();
		t.displayData();

	}

}
